#!/usr/bin/env bash

cd /autograder/source
cp -rp /autograder/submission/labs dslabs
cd dslabs
for ((i=1;i<=15;i=i+1))
do 
   if [[ $i -ne 7 && $i -ne 11 ]];
   then
   	timeout 120 ./run-tests.py --lab 3 -n $i > /autograder/results/result$i.out
   fi
done
cd /autograder/source
cat /autograder/results/result*.out > /autograder/results/results.out
./gen_output.py /autograder/results/results.out > /autograder/results/results.json
