#!/usr/bin/env bash

start_time=$(date +%s)

cd /autograder/source
cp -rp /autograder/submission/labs dslabs
cd dslabs

for i in {1..20}
do
  current_time=$(date +%s)
  elapsed=$((current_time - start_time))

  if [ $elapsed -ge 1200 ]; then
    echo "Total timeout of 10 minutes exceeded."
    break
  fi

  remaining=$((1200 - elapsed))
  individual_timeout=$((remaining > 120 ? 120 : remaining))

  timeout $individual_timeout ./run-tests.py --lab 2 --part 2 -n $i > "/autograder/results/result$i.out"
done

cd /autograder/source
cat /autograder/results/result*.out > /autograder/results/results.out
./gen_output.py /autograder/results/results.out > /autograder/results/results.json
rm -rf /autograder/source/dslabs/labs/lab2-primarybackup/src
